class args:
    base_model_path = "deberta-v3-base"
    tuned_model_path = "QA-DeBERTa/deberta-v3-base-finetuned.pt"
    max_len = 640
    doc_stride = 128
    vit_info = """Vidyalankar Institute of Technology (VIT) is a renowned engineering college located in Mumbai, India. Established in 1999, VIT offers undergraduate and postgraduate programs in various disciplines such as Computer Engineering, Information Technology, Electronics and Telecommunication Engineering, Electronics and Computer Science Engineering, and Biomedical Engineering. The admission process for undergraduate courses such as B.Tech is based on the candidate's score in the Maharashtra Common Entrance Test (MHT-CET) or Joint Entrance Examination (JEE Main). For postgraduate courses such as M.Tech, the admission process is based on the candidate's score in GATE or CET conducted by the Maharashtra Government. Additionally, candidates must have completed their undergraduate degree in the relevant field with a minimum of 50% marks. VIT has a sprawling campus spread across 11 acres, equipped with state-of-the-art infrastructure, modern amenities, and well-equipped laboratories. The institute boasts of highly qualified and experienced faculty members who are dedicated to providing quality education to the students. VIT also has collaborations with renowned international universities and research organizations, offering students a diverse range of opportunities to expand their horizons. The college has a strong and active placement cell that works towards providing students with placement opportunities in leading companies. Some of the top recruiters include companies like Amazon, Capgemini, Deloitte, IBM, Infosys, L&T Infotech, TCS, and Wipro. The placement cell works closely with the industry to identify job opportunities and provides training to students to prepare them for the recruitment process. As a result of these efforts, VIT has a consistently high placement rate, with many students securing jobs in reputed companies with competitive salaries."""
    ex2_info = """
    The Gateway of India is an iconic monument located in Mumbai, India. It was built in 1924 to commemorate the visit of King George V and Queen Mary to Mumbai, then known as Bombay. The monument is situated at the Apollo Bunder waterfront in South Mumbai, overlooking the Arabian Sea. The Gateway of India has become a symbol of Mumbai's rich history and architectural heritage and is one of the most popular tourist attractions in the city.


The Gateway of India is an impressive example of Indo-Saracenic architecture, which combines elements of Indian, Islamic, and European styles. The monument is built of yellow basalt and reinforced concrete and stands at a height of 26 meters. The central dome of the Gateway is adorned with intricate latticework and is flanked by four turrets. The monument also features two colonnaded halls on either side, which were originally used as waiting rooms for passengers arriving by sea.


Over the years, the Gateway of India has witnessed several historical events, including the departure of the last British troops from India in 1948 and the terrorist attacks in 2008. Today, the monument is a popular gathering spot for tourists and locals alike, who come to enjoy the stunning views of the Arabian Sea and the bustling activity of the waterfront. The Gateway of India is also the starting point for boat rides to the nearby Elephanta Caves, a UNESCO World Heritage site.


In recent years, the Gateway of India has undergone significant restoration and renovation efforts to preserve its heritage and enhance its appeal to visitors. The monument has also been the site of various cultural events, such as music concerts and film festivals. The Gateway of India remains an iconic landmark of Mumbai and a testament to the city's rich history and cultural diversity."""
